-- MySQL Script generated by MySQL Workbench
-- Sun Dec 23 22:00:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jddatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jddatabase` ;

-- -----------------------------------------------------
-- Schema jddatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jddatabase` DEFAULT CHARACTER SET latin1 ;
USE `jddatabase` ;

-- -----------------------------------------------------
-- Table `jddatabase`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`user` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(20) NOT NULL,
  `user_email` VARCHAR(50) NOT NULL,
  `user_tel` VARCHAR(20) NOT NULL,
  `user_password` VARCHAR(20) NOT NULL,
  `user_status` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`addr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`addr` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`addr` (
  `addr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `addr_country` VARCHAR(20) NOT NULL,
  `addr_province` VARCHAR(20) NOT NULL,
  `addr_city` VARCHAR(20) NOT NULL,
  `addr_area` VARCHAR(20) NOT NULL,
  `addr_detail` VARCHAR(50) NOT NULL,
  `addr_is_default` TINYINT(1) NOT NULL DEFAULT 0,
  `addr_name` VARCHAR(20) NOT NULL,
  `addr_tel` VARCHAR(20) NOT NULL,
  `user_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`addr_id`),
  INDEX `fk_addr_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_addr_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`advertise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`advertise` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`advertise` (
  `ad_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ad_location` VARCHAR(50) NOT NULL,
  `ad_channel` VARCHAR(50) NOT NULL,
  `ad_name` VARCHAR(50) NOT NULL,
  `ad_detail` VARCHAR(50) NOT NULL,
  `ad_type` VARCHAR(50) NOT NULL,
  `ad_media_width` FLOAT NOT NULL,
  `ad_media_height` FLOAT NOT NULL,
  `ad_media_type` VARCHAR(20) NOT NULL,
  `ad_media_size` FLOAT NOT NULL,
  `ad_create_time` DATETIME NOT NULL,
  `ad_update_time` DATETIME NOT NULL,
  PRIMARY KEY (`ad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`store` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`store` (
  `store_id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(20) NOT NULL,
  `store_keyword` VARCHAR(20) NOT NULL,
  `store_tel` VARCHAR(20) NOT NULL,
  `store_is_direct_sale` TINYINT(1) NOT NULL DEFAULT 0,
  `store_url` VARCHAR(50) NOT NULL,
  `store_logo_url` VARCHAR(50) NOT NULL,
  `store_license_url` VARCHAR(50) NOT NULL,
  `store_introduction` VARCHAR(50) NOT NULL,
  `store_status` INT(11) NOT NULL DEFAULT 1,
  `store_create_time` DATETIME NOT NULL,
  `store_pass_time` DATETIME NOT NULL,
  `store_end_time` DATETIME NOT NULL,
  `store_verifier` VARCHAR(20) NOT NULL,
  `user_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`store_id`),
  INDEX `fk_store_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_store_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`advertise_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`advertise_info` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`advertise_info` (
  `ad_info_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ad_info_title` VARCHAR(20) NOT NULL,
  `ad_file_path` VARCHAR(50) NOT NULL,
  `ad_file_type` VARCHAR(20) NOT NULL,
  `ad_file_size` FLOAT NOT NULL,
  `ad_link_url` VARCHAR(50) NOT NULL,
  `ad_scan_time` INT(11) NOT NULL DEFAULT 0,
  `ad_click_time` INT(11) NOT NULL DEFAULT 0,
  `ad_is_period` TINYINT(1) NOT NULL DEFAULT 1,
  `ad_create_time` DATETIME NOT NULL,
  `ad_during_time` DATETIME NOT NULL,
  `ad_begin_time` DATETIME NOT NULL,
  `ad_end_time` DATETIME NOT NULL,
  `ad_info_status` INT(11) NOT NULL DEFAULT 1,
  `ad_note` VARCHAR(50) NULL DEFAULT NULL,
  `store_store_id` INT(11) NOT NULL,
  `advertise_ad_id` INT(11) NOT NULL,
  PRIMARY KEY (`ad_info_id`),
  INDEX `fk_advertise_info_store1_idx` (`store_store_id` ASC),
  INDEX `fk_advertise_info_advertise1_idx` (`advertise_ad_id` ASC),
  CONSTRAINT `fk_advertise_info_store1`
    FOREIGN KEY (`store_store_id`)
    REFERENCES `jddatabase`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_advertise_info_advertise1`
    FOREIGN KEY (`advertise_ad_id`)
    REFERENCES `jddatabase`.`advertise` (`ad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`attr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`attr` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`attr` (
  `attr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `attr_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`attr_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`attr_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`attr_value` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`attr_value` (
  `attr_value_id` INT(11) NOT NULL AUTO_INCREMENT,
  `attr_value_name` VARCHAR(50) NOT NULL,
  `attr_attr_id` INT(11) NOT NULL,
  PRIMARY KEY (`attr_value_id`),
  INDEX `fk_attr_value_attr1_idx` (`attr_attr_id` ASC),
  CONSTRAINT `fk_attr_value_attr1`
    FOREIGN KEY (`attr_attr_id`)
    REFERENCES `jddatabase`.`attr` (`attr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`brand` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`brand` (
  `brand_id` INT(11) NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`coupon` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`coupon` (
  `coupon_id` INT(11) NOT NULL AUTO_INCREMENT,
  `coupon_name` VARCHAR(20) NOT NULL,
  `coupon_how_many` INT(11) NOT NULL,
  `coupon_type` FLOAT NOT NULL DEFAULT 1,
  `coupon_lower_bound` FLOAT NOT NULL,
  `coupon_value` FLOAT NOT NULL,
  `coupon_cost_allocation` INT(11) NOT NULL DEFAULT 0,
  `coupon_user_lever` VARCHAR(20) NOT NULL,
  `coupon_use_range` INT(11) NOT NULL DEFAULT 1,
  `coupon_begin_time` DATETIME NOT NULL,
  `coupon_end_time` DATETIME NOT NULL,
  `coupon_status` INT(11) NOT NULL DEFAULT 1,
  `coupon_verifier` VARCHAR(20) NOT NULL,
  `coupon_is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `coupon_note` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`coupon_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`coupon_use_range`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`coupon_use_range` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`coupon_use_range` (
  `coupon_use_range_id` INT(11) NOT NULL AUTO_INCREMENT,
  `coupon_coupon_id` INT(11) NOT NULL,
  `use_range_id` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`coupon_use_range_id`),
  INDEX `fk_coupon_use_range_coupon1_idx` (`coupon_coupon_id` ASC),
  CONSTRAINT `fk_coupon_use_range_coupon1`
    FOREIGN KEY (`coupon_coupon_id`)
    REFERENCES `jddatabase`.`coupon` (`coupon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`pay_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`pay_channel` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`pay_channel` (
  `pay_channel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pay_channel_type` INT(11) NOT NULL DEFAULT 1,
  `pay_channel_type_no` VARCHAR(20) NOT NULL,
  `user_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`pay_channel_id`),
  INDEX `fk_pay_channel_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_pay_channel_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`order` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`order` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(20) NOT NULL,
  `order_sku_sum` INT(11) NOT NULL DEFAULT 0,
  `order_total_price` FLOAT NOT NULL DEFAULT 0,
  `order_real_price` FLOAT NOT NULL DEFAULT 0,
  `order_delivery_price` FLOAT NOT NULL DEFAULT 0,
  `order_store_discount` FLOAT NOT NULL DEFAULT 0,
  `order_platform_discount` FLOAT NOT NULL DEFAULT 0,
  `order_time_order` DATETIME NOT NULL,
  `order_time_pay` DATETIME NOT NULL,
  `order_time_delivery` DATETIME NOT NULL,
  `order_time_deal` DATETIME NOT NULL,
  `order_delivery_no` VARCHAR(20) NOT NULL,
  `order_note` VARCHAR(50) NULL DEFAULT NULL,
  `order_status` INT(11) NOT NULL DEFAULT 1,
  `pay_channel_pay_channel_id` INT(11) NOT NULL,
  `user_user_id` INT(11) NOT NULL,
  `addr_addr_id` INT(11) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_pay_channel1_idx` (`pay_channel_pay_channel_id` ASC),
  INDEX `fk_order_user1_idx` (`user_user_id` ASC),
  INDEX `fk_order_addr1_idx` (`addr_addr_id` ASC),
  CONSTRAINT `fk_order_pay_channel1`
    FOREIGN KEY (`pay_channel_pay_channel_id`)
    REFERENCES `jddatabase`.`pay_channel` (`pay_channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_addr1`
    FOREIGN KEY (`addr_addr_id`)
    REFERENCES `jddatabase`.`addr` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`return_addr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`return_addr` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`return_addr` (
  `return_addr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `return_addr_country` VARCHAR(20) NOT NULL,
  `return_addr_province` VARCHAR(20) NOT NULL,
  `return_addr_city` VARCHAR(20) NOT NULL,
  `return_addr_area` VARCHAR(20) NOT NULL,
  `return_addr_detail` VARCHAR(50) NOT NULL,
  `return_addr_is_default` TINYINT(1) NOT NULL DEFAULT 0,
  `return_addr_name` VARCHAR(20) NOT NULL,
  `return_addr_tel` VARCHAR(20) NOT NULL,
  `store_store_id` INT(11) NOT NULL,
  PRIMARY KEY (`return_addr_id`),
  INDEX `fk_return_addr_store1_idx` (`store_store_id` ASC),
  CONSTRAINT `fk_return_addr_store1`
    FOREIGN KEY (`store_store_id`)
    REFERENCES `jddatabase`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`return`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`return` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`return` (
  `return_id` INT(11) NOT NULL,
  `return_no` INT(11) NOT NULL,
  `return_delivery_no` VARCHAR(20) NOT NULL,
  `return_amount` INT(11) NOT NULL,
  `return_status` INT(11) NOT NULL DEFAULT 0,
  `return_apply_time` DATETIME NOT NULL,
  `return_start_time` DATETIME NOT NULL,
  `return_end_time` DATETIME NOT NULL,
  `return_reason` VARCHAR(50) NULL DEFAULT NULL,
  `return_note` VARCHAR(50) NULL DEFAULT NULL,
  `order_order_id` INT(11) NOT NULL,
  `user_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`return_id`),
  INDEX `fk_return_order1_idx` (`order_order_id` ASC),
  INDEX `fk_return_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_return_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `jddatabase`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_return_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`shopping_cart` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`shopping_cart` (
  `shopping_cart_id` INT(11) NOT NULL AUTO_INCREMENT,
  `shopping_cart_sku_num` INT(11) NOT NULL DEFAULT 1,
  `shopping_cart_create_time` DATETIME NOT NULL,
  `shopping_cart_is_exist` TINYINT(1) NOT NULL DEFAULT 1,
  `user_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`shopping_cart_id`),
  INDEX `fk_shopping_cart_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_shopping_cart_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spu_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spu_type` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spu_type` (
  `spu_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `spu_type_name` VARCHAR(50) NOT NULL,
  `spu_type_father_id` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`spu_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spu` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spu` (
  `spu_id` INT(11) NOT NULL,
  `spu_name` VARCHAR(50) NOT NULL,
  `store_store_id` INT(11) NOT NULL,
  `brand_brand_id` INT(11) NOT NULL,
  `spu_type_spu_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`spu_id`),
  INDEX `fk_spu_store1_idx` (`store_store_id` ASC),
  INDEX `fk_spu_brand1_idx` (`brand_brand_id` ASC),
  INDEX `fk_spu_spu_type1_idx` (`spu_type_spu_type_id` ASC),
  CONSTRAINT `fk_spu_store1`
    FOREIGN KEY (`store_store_id`)
    REFERENCES `jddatabase`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spu_brand1`
    FOREIGN KEY (`brand_brand_id`)
    REFERENCES `jddatabase`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spu_spu_type1`
    FOREIGN KEY (`spu_type_spu_type_id`)
    REFERENCES `jddatabase`.`spu_type` (`spu_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`sku` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`sku` (
  `sku_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sku_name` VARCHAR(50) NOT NULL,
  `spu_spu_id` INT(11) NOT NULL,
  PRIMARY KEY (`sku_id`),
  INDEX `fk_sku_spu1_idx` (`spu_spu_id` ASC),
  CONSTRAINT `fk_sku_spu1`
    FOREIGN KEY (`spu_spu_id`)
    REFERENCES `jddatabase`.`spu` (`spu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spec_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spec_group` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spec_group` (
  `spec_group_id` INT(11) NOT NULL AUTO_INCREMENT,
  `spec_group_name` SET('color', 'storage') NOT NULL,
  PRIMARY KEY (`spec_group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spec` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spec` (
  `spec_id` INT(11) NOT NULL AUTO_INCREMENT,
  `spec_name` SET('red', '32GB') NOT NULL,
  `spec_group_spec_group_id` INT(11) NOT NULL,
  PRIMARY KEY (`spec_id`),
  INDEX `fk_spec_spec_group1_idx` (`spec_group_spec_group_id` ASC),
  CONSTRAINT `fk_spec_spec_group1`
    FOREIGN KEY (`spec_group_spec_group_id`)
    REFERENCES `jddatabase`.`spec_group` (`spec_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`user_info` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`user_info` (
  `user_info_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_info_realname` VARCHAR(20) NOT NULL,
  `user_info_sex` VARCHAR(2) NOT NULL DEFAULT 0,
  `user_info_pid` VARCHAR(50) NOT NULL,
  `user_info_birth` DATE NULL DEFAULT NULL,
  `user_info_face_url` VARCHAR(50) NULL DEFAULT NULL,
  `user_info_level` VARCHAR(20) NOT NULL,
  `user_info_cost` FLOAT NOT NULL,
  `user_info_return_credit` INT(11) NULL DEFAULT NULL,
  `user_info_regist_time` DATETIME NOT NULL,
  `user_info_login_time` DATETIME NOT NULL,
  `user_info_login_count` INT(11) NOT NULL,
  `user_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_info_id`),
  INDEX `fk_user_info_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_info_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`user_login_open`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`user_login_open` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`user_login_open` (
  `user_login_open_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_login_open_qq_no` VARCHAR(20) NULL DEFAULT NULL,
  `user_login_open_wechat_no` VARCHAR(20) NULL DEFAULT NULL,
  `user_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_login_open_id`),
  INDEX `fk_user_login_open_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_login_open_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spu_has_spec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spu_has_spec` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spu_has_spec` (
  `spu_spu_id` INT(11) NOT NULL,
  `spec_spec_id` INT(11) NOT NULL,
  PRIMARY KEY (`spu_spu_id`, `spec_spec_id`),
  INDEX `fk_spu_has_spec_spec1_idx` (`spec_spec_id` ASC),
  INDEX `fk_spu_has_spec_spu1_idx` (`spu_spu_id` ASC),
  CONSTRAINT `fk_spu_has_spec_spu1`
    FOREIGN KEY (`spu_spu_id`)
    REFERENCES `jddatabase`.`spu` (`spu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spu_has_spec_spec1`
    FOREIGN KEY (`spec_spec_id`)
    REFERENCES `jddatabase`.`spec` (`spec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`sku_has_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`sku_has_order` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`sku_has_order` (
  `sku_sku_id` INT(11) NOT NULL,
  `order_order_id` INT(11) NOT NULL,
  `sku_has_order_sku_num` INT NOT NULL,
  PRIMARY KEY (`sku_sku_id`, `order_order_id`),
  INDEX `fk_sku_has_order_order1_idx` (`order_order_id` ASC),
  INDEX `fk_sku_has_order_sku1_idx` (`sku_sku_id` ASC),
  CONSTRAINT `fk_sku_has_order_sku1`
    FOREIGN KEY (`sku_sku_id`)
    REFERENCES `jddatabase`.`sku` (`sku_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sku_has_order_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `jddatabase`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spu_type_has_spec_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spu_type_has_spec_group` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spu_type_has_spec_group` (
  `spu_type_spu_type_id` INT(11) NOT NULL,
  `spec_group_spec_group_id` INT(11) NOT NULL,
  PRIMARY KEY (`spu_type_spu_type_id`, `spec_group_spec_group_id`),
  INDEX `fk_spu_type_has_spec_group_spec_group1_idx` (`spec_group_spec_group_id` ASC),
  INDEX `fk_spu_type_has_spec_group_spu_type1_idx` (`spu_type_spu_type_id` ASC),
  CONSTRAINT `fk_spu_type_has_spec_group_spu_type1`
    FOREIGN KEY (`spu_type_spu_type_id`)
    REFERENCES `jddatabase`.`spu_type` (`spu_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spu_type_has_spec_group_spec_group1`
    FOREIGN KEY (`spec_group_spec_group_id`)
    REFERENCES `jddatabase`.`spec_group` (`spec_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spu_type_has_store_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spu_type_has_store_info` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spu_type_has_store_info` (
  `spu_type_spu_type_id` INT(11) NOT NULL,
  `store_info_store_id` INT(11) NOT NULL,
  PRIMARY KEY (`spu_type_spu_type_id`, `store_info_store_id`),
  INDEX `fk_spu_type_has_store_info_store_info1_idx` (`store_info_store_id` ASC),
  INDEX `fk_spu_type_has_store_info_spu_type1_idx` (`spu_type_spu_type_id` ASC),
  CONSTRAINT `fk_spu_type_has_store_info_spu_type1`
    FOREIGN KEY (`spu_type_spu_type_id`)
    REFERENCES `jddatabase`.`spu_type` (`spu_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spu_type_has_store_info_store_info1`
    FOREIGN KEY (`store_info_store_id`)
    REFERENCES `jddatabase`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`sku_has_return`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`sku_has_return` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`sku_has_return` (
  `sku_sku_id` INT(11) NOT NULL,
  `return_return_id` INT(11) NOT NULL,
  PRIMARY KEY (`sku_sku_id`, `return_return_id`),
  INDEX `fk_sku_has_return_return1_idx` (`return_return_id` ASC),
  INDEX `fk_sku_has_return_sku1_idx` (`sku_sku_id` ASC),
  CONSTRAINT `fk_sku_has_return_sku1`
    FOREIGN KEY (`sku_sku_id`)
    REFERENCES `jddatabase`.`sku` (`sku_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sku_has_return_return1`
    FOREIGN KEY (`return_return_id`)
    REFERENCES `jddatabase`.`return` (`return_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`attr_value_has_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`attr_value_has_sku` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`attr_value_has_sku` (
  `attr_value_attr_value_id` INT(11) NOT NULL,
  `sku_sku_id` INT(11) NOT NULL,
  PRIMARY KEY (`attr_value_attr_value_id`, `sku_sku_id`),
  INDEX `fk_attr_value_has_sku_sku1_idx` (`sku_sku_id` ASC),
  INDEX `fk_attr_value_has_sku_attr_value1_idx` (`attr_value_attr_value_id` ASC),
  CONSTRAINT `fk_attr_value_has_sku_attr_value1`
    FOREIGN KEY (`attr_value_attr_value_id`)
    REFERENCES `jddatabase`.`attr_value` (`attr_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attr_value_has_sku_sku1`
    FOREIGN KEY (`sku_sku_id`)
    REFERENCES `jddatabase`.`sku` (`sku_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`spec_has_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`spec_has_sku` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`spec_has_sku` (
  `spec_spec_id` INT(11) NOT NULL,
  `sku_sku_id` INT(11) NOT NULL,
  PRIMARY KEY (`spec_spec_id`, `sku_sku_id`),
  INDEX `fk_spec_has_sku_sku1_idx` (`sku_sku_id` ASC),
  INDEX `fk_spec_has_sku_spec1_idx` (`spec_spec_id` ASC),
  CONSTRAINT `fk_spec_has_sku_spec1`
    FOREIGN KEY (`spec_spec_id`)
    REFERENCES `jddatabase`.`spec` (`spec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spec_has_sku_sku1`
    FOREIGN KEY (`sku_sku_id`)
    REFERENCES `jddatabase`.`sku` (`sku_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`order_has_coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`order_has_coupon` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`order_has_coupon` (
  `order_order_id` INT(11) NOT NULL,
  `coupon_coupon_id` INT(11) NOT NULL,
  PRIMARY KEY (`order_order_id`, `coupon_coupon_id`),
  INDEX `fk_order_has_coupon_coupon1_idx` (`coupon_coupon_id` ASC),
  INDEX `fk_order_has_coupon_order1_idx` (`order_order_id` ASC),
  CONSTRAINT `fk_order_has_coupon_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `jddatabase`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_coupon_coupon1`
    FOREIGN KEY (`coupon_coupon_id`)
    REFERENCES `jddatabase`.`coupon` (`coupon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`coupon_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`coupon_has_user` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`coupon_has_user` (
  `coupon_coupon_id` INT(11) NOT NULL,
  `user_user_id` INT(11) NOT NULL,
  `received_time` DATETIME NOT NULL,
  `coupon_has_user_is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `coupon_has_user_status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`coupon_coupon_id`, `user_user_id`),
  INDEX `fk_coupon_has_user_user1_idx` (`user_user_id` ASC),
  INDEX `fk_coupon_has_user_coupon1_idx` (`coupon_coupon_id` ASC),
  CONSTRAINT `fk_coupon_has_user_coupon1`
    FOREIGN KEY (`coupon_coupon_id`)
    REFERENCES `jddatabase`.`coupon` (`coupon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coupon_has_user_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `jddatabase`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jddatabase`.`shopping_cart_has_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jddatabase`.`shopping_cart_has_sku` ;

CREATE TABLE IF NOT EXISTS `jddatabase`.`shopping_cart_has_sku` (
  `shopping_cart_shopping_cart_id` INT(11) NOT NULL,
  `sku_sku_id` INT(11) NOT NULL,
  PRIMARY KEY (`shopping_cart_shopping_cart_id`, `sku_sku_id`),
  INDEX `fk_shopping_cart_has_sku_sku1_idx` (`sku_sku_id` ASC),
  INDEX `fk_shopping_cart_has_sku_shopping_cart1_idx` (`shopping_cart_shopping_cart_id` ASC),
  CONSTRAINT `fk_shopping_cart_has_sku_shopping_cart1`
    FOREIGN KEY (`shopping_cart_shopping_cart_id`)
    REFERENCES `jddatabase`.`shopping_cart` (`shopping_cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_has_sku_sku1`
    FOREIGN KEY (`sku_sku_id`)
    REFERENCES `jddatabase`.`sku` (`sku_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
